# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
        
# Setup
title:               Olivia Wang
tagline:             'A web developer, love reading and walking.'
description:         "say hi"
url:                 http://voidove.github.io/
baseurl:             /
avatar:				 media/images/olivia-avatar.jpg
paginate:            5
locale:         	 en_us

# About/contact
author:
  name:              Olivia Wang
  email:             oliviawang1208@hotmail.com
fb_admins:      	 http://facebook.com/danyal.zia.k
fb_appid:       	 337414769782635

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
